unique_ids:
  assets:
    standard-page.html: O6IZ5IOC5TTRW2UM4Y42AOKD6TQ2EL7X
    theme.css: KKADEZFZ6GGWTYDXCGWUN5MX32NHAIAZ
  forms:
    Form1: OTCPODN4KFKUBTIEO2FV4FKOAEU6X4KV
  modules: {}
  scripts: {}
  server_modules: {}
